// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #DshInput is the `dsh` verb's plugin_input: the method name plus its
// method-exclusive modifiers.
type DshInput struct {
	// method — the dsh verb method name (the verb's PRIMARY input field, so
	// `dsh: version` desugars to {method: "version"}).
	Method string `yaml:"method,omitempty" json:"method"`

	// profile — the profile name for plugin-list (default "web", the profile the
	// dsh candy's service boots).
	Profile string `yaml:"profile,omitempty" json:"profile,omitempty"`
}
